### ISSUE TITLE
New Module Layout on left panel selection

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#133]

**Comment by timmwille** [comment]
![grafik](https://github.com/ASKnetCommunity/Training/assets/8081055/6b50baf5-a6fd-4908-8bd0-45fbf563e6ce)

**Comment by walthierer** [comment]
checkout post: https://github.com/ASKnetCommunity/Training/issues/77#issuecomment-1825626481

**Comment by timmwille** [comment]
> checkout post: [#77 (comment)](https://github.com/ASKnetCommunity/Training/issues/77#issuecomment-1825626481)

I think it is nicer to talk about specifics of the left panel view of each module here. 


One think in the comment mentioned is different from what we need is the overall Module time that is displayed! This should still be included!

**Comment by timmwille** [comment]
if a section of the image is shown, we should go for the top part. I like the draft @walthierer thank you

**Comment by walthierer** [comment]
i think @saisilinus already solved almost all the points on this issue. they only thing which comes to my mind is the icon for total time. 
if i remember right @bmen used a sandglass icon in his aproach on the single module view whereas @saisilinus used another watch icon. since the difficulty level also has something watch like i would recomend to use the sandglass / hourglass icon (the thing with sand) to have some consistency and clarificatio.
