### ISSUE TITLE
Tags seperated by space

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#153]
Example Tag for this issue is: `Open Source&Knowledge`

in the module files it was written like this: `Open_Source&Knowledge` it would be preferable to write it like `Open Source&Knowledge`with a space between Open and Source. But if you do so it will create two Tags one `Open` and `Source`. This is not what we want :)) 

Tags in the module file should be only seperated by `,` and not by space to avoid new (meaningless) tags like `Open` in this example

**Comment by bmen** [comment]
@timmwille 
The official documentation for Jekyll says that the tags are separated by a space. These are then converted into the following arrays: ["classic", "hollywood"]
https://jekyllrb.com/docs/posts/#tags
I would therefore recommend following the Jekyll standard and using spaces as separators

**Comment by saisilinus** [comment]
I just checked the official Jekyll documentation @bmen and @timmwille  and it's limited in application because tags are separated by a space. If we decide to go with that approach we'll end up with tags like `Open_Source&Knowledge` rather than the ideal `Open Source & Knowledge`. We have two options that we can use:

- `'Open Source & Knowledge, Web & Software'` - The tags/authors/resources are comma-separated and more user-friendly. We do the conversion to `['Open Source & Knowledge', 'Web & Software']` under the hood.
- `['Open Source & Knowledge', 'Web & Software']` - It gets rid of the extra step of conversion from `'Open Source & Knowledge, Web & Software'` to `['Open Source & Knowledge', 'Web & Software']` but is similar.

Both options are technically feasible so I think the question is which one is the most ideal for the editors?

**Comment by bmen** [comment]
Have you @timmwille  now decided which option would be better for the authors?

- 'Open Source & Knowledge, Web & Software'
or
- ['Open Source & Knowledge', 'Web & Software']

**Comment by bmen** [comment]
ah, that's done. I've just seen the ticket: #160

**Comment by bmen** [comment]
can we close the ticket then?
