### ISSUE TITLE
add a local session cached option so when the page reloads one is able to resume

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#170]
might be linked to #143

**Comment by timmwille** [comment]
@saisilinus I noticed one more bug for the cache: if I put a `time slot` at the end of a module (not between) it gets deleted after reload :) the rest is cached perfectly to my observation.

**Comment by saisilinus** [comment]
Hmmm...very strange. I will check it out

**Comment by saisilinus** [comment]
I think the bug has to do with timing. When you add something to the configurator, several things such as time calculations and the insertions of daybreaks and timebreaks happen in the background. The cache is refreshed after all these steps so it could take a second or 2. If you reload the page before the cache is refreshed, you lose your latest changes.

I've added a `Saving` indicator that shows the user when the cache is refreshing so that you don't reload before it does.
