### ISSUE TITLE
Improvements to the left module selection area 

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#77]
- [x] #45 
- [x] #75 
- [x] #105
- [x] #106
- [x] #46 
- [x] #107

**Comment by timmwille** [comment]
We might re-consider some design questions like #44 when looking at the progress of #111 that has a ton of nice design ideas that also @walthierer mentioned 

follow #130 draft

**Comment by walthierer** [comment]
little graphical bug i spotted: the info icon / button has a higher z-value than the time / day break slots
<img width="293" alt="Bildschirmfoto 2023-11-24 um 13 12 35" src="https://github.com/ASKnetCommunity/Training/assets/64423638/be5000c5-ab32-41ae-8aa4-42d1c936dfee">

**Comment by walthierer** [comment]
if we want to use the design approach of @bmen ´s overview page - which i strongly recommend - i think there are only two possible solutions: a bit tighten with images or without images
![ASKtraining_configurator_left_pannel_1](https://github.com/ASKnetCommunity/Training/assets/64423638/0820ffd0-f31a-4cd9-a484-f19c23033aec)
![ASKtraining_configurator_left_pannel_2](https://github.com/ASKnetCommunity/Training/assets/64423638/6202a191-d10d-4e22-b3a0-45d4f441384a)

note: in this design proposals the search bar is missing --> the available space will be a bit less then in my proposals 

the third one is with the images in original size (overview page), the spaces in between (text, image, etc.) is a bit tighten. i would not recommend this one, because it displays only one module in total

![ASKtraining_configurator_left_pannel_3](https://github.com/ASKnetCommunity/Training/assets/64423638/be119a4f-ebb5-48ce-98ac-129a9e60ba95)

**Comment by timmwille** [comment]
Maybe one other option would be to show always just the top of the image but when you select it or hover over the image section it expands?

**Comment by timmwille** [comment]
@walthierer is it fine if we move the left module layout and the lightbox to release 1.1? I think right now it will be a time killer on monday risking no release at all
